        0==""//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers the number 0 and the empty string '' to be equal, as both are falsy values in JavaScript.
        0=="0"//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers the number 0 and the string '0' to be equal, as both represent the same numeric value.
        0==false//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers the number 0 and the boolean value false to be equal, as both are falsy values in JavaScript.
        null==undefined//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers null and undefined to be equal, as both represent the absence of a value in JavaScript.
        "\t\n"==0//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers the string containing only whitespace characters (tab and newline) to be equal to the number 0, as both are falsy values in JavaScript.
        //Rule breaking examples;
        null==0//This will print false to the console because when using the loose equality operator (==), JavaScript does not consider null and 0 to be equal, as null represents the intentional absence of any object value, while 0 is a numeric value.
        null==false//This will print false to the console because when using the loose equality operator (==), JavaScript does not consider null and false to be equal, as null represents the intentional absence of any object value, while false is a boolean value.
        undefined==0//This will print false to the console because when using the loose equality operator (==), JavaScript does not consider undefined and 0 to be equal, as undefined represents a variable that has been declared but has not been assigned a value, while 0 is a numeric value.
        undefined==""//This will print false to the console because when using the loose equality operator (==), JavaScript does not consider undefined and an empty string '' to be equal, as undefined represents a variable that has been declared but has not been assigned a value, while an empty string is a string value.
        undefined==false//This will print false to the console because when using the loose equality operator (==), JavaScript does not consider undefined and false to be equal, as undefined represents a variable that has been declared but has not been assigned a value, while false is a boolean value.
        NaN==NaN//This will print false to the console because in JavaScript, NaN (Not-a-Number) is not equal to anything, including itself. Therefore, NaN == NaN evaluates to false.
        console.log(0=="")//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers the number 0 and the empty string '' to be equal, as both are falsy values in JavaScript.
        console.log(0==="")//This will print false to the console because when using the strict equality operator (===), JavaScript does not perform type coercion and considers the number 0 and the empty string '' to be different types and values, resulting in false.
        console.log(null==undefined)//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers null and undefined to be equal, as both represent the absence of a value in JavaScript.
        console.log(null===undefined)//This will print false to the console because when using the strict equality operator (===), JavaScript does not perform type coercion and considers null and undefined to be different types and values, resulting in false.
        console.log(0==false)//This will print true to the console because when using the loose equality operator (==), JavaScript performs type coercion and considers the number 0 and the boolean value false to be equal, as both are falsy values in JavaScript.
        console.log(0===false)//This will print false to the console because when using the strict equality operator (===), JavaScript does not perform type coercion and considers the number 0 and the boolean value false to be different types and values, resulting in false.  
